version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  web:
    image: lyft_platform
    volumes:
      - .:/code

    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - "db"

    command: "python manage.py runserver 0.0.0.0:8000"