# Generated by Django 2.1.5 on 2019-01-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyfterservice',
            name='destination_lat',
            field=models.DecimalField(decimal_places=100, max_digits=150),
        ),
        migrations.AlterField(
            model_name='lyfterservice',
            name='destination_long',
            field=models.DecimalField(decimal_places=100, max_digits=150),
        ),
        migrations.AlterField(
            model_name='lyfterservice',
            name='source_lat',
            field=models.DecimalField(decimal_places=100, max_digits=150),
        ),
        migrations.AlterField(
            model_name='lyfterservice',
            name='source_long',
            field=models.DecimalField(decimal_places=100, max_digits=150),
        ),
    ]
