# Generated by Django 2.1.5 on 2019-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190118_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyfterservice',
            name='destination_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lyfterservice',
            name='destination_long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lyfterservice',
            name='lyftee_max_limit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lyfterservice',
            name='source_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lyfterservice',
            name='source_long',
            field=models.FloatField(),
        ),
    ]
