# Generated by Django 2.1.5 on 2019-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190118_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyfteeschedule',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
