# Generated by Django 2.1.5 on 2019-01-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190118_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyfteeschedule',
            name='destination_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lyfteeschedule',
            name='destination_long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lyfteeschedule',
            name='source_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lyfteeschedule',
            name='source_long',
            field=models.FloatField(),
        ),
    ]
