# Generated by Django 2.1.5 on 2019-01-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190118_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyfteeschedule',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
