# Generated by Django 2.1.5 on 2019-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_lyfteeschedule_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyfterservice',
            name='lyftee_max_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
